language: node_js

node_js:
  - "18"

services:
  - docker

install:
  - npm install

before_script:
  - docker --version
  - docker build -t proyecto-docker-app .

script:
  - echo "Validando Travis CI"
  - node --version
  - npm --version
  - docker images
