name: CI Docker Node

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Verificar Docker
        run: docker --version

      - name: Construir imagen Docker
        run: docker build -t proyecto-docker-app .

      - name: Verificar archivos del proyecto
        run: ls -la

      - name: Finalizar validación
        run: echo "Integración continua ejecutada correctamente con GitHub Actions"